import Head from 'next/head'
import styles from '../styles/Home.module.css'

//import Link
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className="m-40">
      <h1 className="text-3xl text-cyan-500">
      Tailwind CSS 3 with{' '}
      <span className="font-sans text-gray-700 shadow-md shadow-cyan-500/30 px-2 py-2 font-light rounded-full">
      Next.JS
      </span>
      </h1>
      </div>

        <p className={styles.description}>
          <Link href="/books">
              <button className="btn btn-primary border-0 shadow-sm mb-3">Tabel Buku</button>
          </Link>
        </p>
        </main>
    </div>
  )
}
